#!/bin/bash

export CLASSPATH="/home/ec2-user/CNV-2019/:/home/ec2-user/CNV-2019/pt/ulisboa/tecnico/cnv/instrumentation/"
export _JAVA_OPTIONS="-XX:-UseSplitVerifier"

cd pt/ulisboa/tecnico/cnv/solver/
# Solver_.class é  a versão que vem no zip original
java BasicBlockCount ./Solver_.class  ./output
# Guardo numa pasta diferente para poder manter esse ficheiro como backup e não o reescrever
# Aqui reescrevo o que já está instrumentalizado, com uma versão anterior.
cp output/Solver_.class ./Solver.class

cd /home/ec2-user/CNV-2019/


java pt/ulisboa/tecnico/cnv/server/WebServer

